### ISSUE TITLE
Support encryption environment

### ISSUE THREAD

**Issue by janbiasi** [coollabsio/pocketbase#31]
Would it be an option to switch from `CMD` to `ENTRYPOINT` to support [setting the encryptionEnv](https://pocketbase.io/docs/going-to-production/#enable-settings-encryption) via the `docker-compose.yml` file? I'd be open to submit a PR for that if nothing speaks against the change :) 

My goal:

```yml
services:
  pocketbase:
    image: 'ghcr.io/coollabsio/pocketbase:latest'
    environment:
      - SERVICE_FQDN_POCKETBASE_8080
      - ENCRYPTION_KEY=$ENCRYPTION_KEY
    command:
      - --encryptionEnv 
      - ENCRYPTION_KEY
    volumes:
      - 'pocketbase-data:/app/pb_data'
      - 'pocketbase-hooks:/app/pb_hooks'
      - 'pocketbase-migrations:/app/pb_migrations'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```

_Background: I don't want to submit plain text secrets when creating backups to an external storage._
